#!/bin/bash

test_description='notmuch cat'
. ./test-lib.sh

test_begin_subtest "Generate some messages"
generate_message
generate_message
output=$(NOTMUCH_NEW)
test_expect_equal "$output" "Added 2 new messages to the database."

test_begin_subtest "Without arguments"
output=$(notmuch cat 2>&1)
test_expect_equal "$output" "Error: notmuch cat requires at least one search term."

test_begin_subtest "Attempt to cat multiple messages"
output=$(notmuch cat "*" 2>&1)
test_expect_equal "$output" "Error: search term did not match precisely one message."

test_begin_subtest "Cat a message"
output=$(notmuch cat id:msg-001@notmuch-test-suite)
test_expect_equal "$output" "From: Notmuch Test Suite <test_suite@notmuchmail.org>
To: Notmuch Test Suite <test_suite@notmuchmail.org>
Message-Id: <msg-001@notmuch-test-suite>
Subject: Test message #1
Date: Tue, 05 Jan 2001 15:43:57 -0000

This is just a test message (#1)"

test_begin_subtest "Cat another message"
output=$(notmuch cat id:msg-002@notmuch-test-suite)
test_expect_equal "$output" "From: Notmuch Test Suite <test_suite@notmuchmail.org>
To: Notmuch Test Suite <test_suite@notmuchmail.org>
Message-Id: <msg-002@notmuch-test-suite>
Subject: Test message #2
Date: Tue, 05 Jan 2001 15:43:57 -0000

This is just a test message (#2)"

test_done
