#!/bin/bash
test_description="emacs interface"
. test-lib.sh

add_email_corpus

test_begin_subtest "Test emacs-hello interface"
output=$(test_emacs '(notmuch-hello) (message (buffer-string))' 2>&1)
test_expect_equal "$output" "   Welcome to notmuch. You have 50 messages.

Saved searches: [edit]

	  50 inbox           50 unread    

Search:                                                                     

[Show all tags]

	 Type a search query and hit RET to view matching threads.
		Edit saved searches with the \`edit' button.
  Hit RET or click on a saved search or tag name to view matching threads.
    \`=' refreshes this screen. \`s' jumps to the search box. \`q' to quit."


test_done
