#!/bin/bash
test_description="emacs interface"
. test-lib.sh

EXPECTED=../emacs.expected-output

add_email_corpus

test_begin_subtest "Basic notmuch-hello view in emacs"
output=$(test_emacs '(notmuch-hello) (message (buffer-string))' 2>&1)
expected=$(cat $EXPECTED/notmuch-hello)
test_expect_equal "$output" "$expected"

test_begin_subtest "Basic notmuch-search view in emacs"
output=$(test_emacs '(notmuch-search "tag:inbox") (notmuch-test-wait) (message (buffer-string))' 2>&1)
expected=$(cat $EXPECTED/notmuch-search-tag-inbox)
test_expect_equal "$output" "$expected"

test_begin_subtest "Navigation of notmuch-hello to search results
	[XXX: Need to decide the correct order of the search results]"
output=$(test_emacs '(notmuch-hello) (goto-char (point-min)) (re-search-forward "inbox") (widget-button-press (point)) (notmuch-test-wait) (message (buffer-string))' 2>&1)
test_expect_equal_failure "$output" "$expected"

test_begin_subtest "Basic notmuch-show view in emacs"
output=$(test_emacs '(notmuch-show "thread:0000000000000009") (message (buffer-string))' 2>&1)
expected=$(cat $EXPECTED/notmuch-show-thread-9)
test_expect_equal "$output" "$expected"

test_begin_subtest "Navigation of notmuch-search to thread view"
output=$(test_emacs '(notmuch-search "tag:inbox") (notmuch-test-wait) (goto-char (point-min)) (re-search-forward "Working with Maildir") (notmuch-search-show-thread) (notmuch-test-wait) (message (buffer-string))' 2>&1)
test_expect_equal "$output" "$expected"

test_begin_subtest "Add tag from search view"
test_emacs '(notmuch-search "thread:0000000000000001") (notmuch-test-wait) (notmuch-search-add-tag "tag-from-search-view")'
output=$(notmuch search thread:0000000000000001)
test_expect_equal "$output" "thread:0000000000000001   2009-11-18 [4/4] Jjgod Jiang, Alexander Botero-Lowry; [notmuch] Mac OS X/Darwin compatibility issues (inbox tag-from-search-view unread)"

test_begin_subtest "Remove tag from search view"
test_emacs '(notmuch-search "thread:0000000000000001") (notmuch-test-wait) (notmuch-search-remove-tag "tag-from-search-view")'
output=$(notmuch search thread:0000000000000001)
test_expect_equal "$output" "thread:0000000000000001   2009-11-18 [4/4] Jjgod Jiang, Alexander Botero-Lowry; [notmuch] Mac OS X/Darwin compatibility issues (inbox unread)"

test_begin_subtest "Add tag from notmuch-show view"
test_emacs '(notmuch-show "thread:0000000000000001") (notmuch-show-add-tag "tag-from-show-view")'
output=$(notmuch search thread:0000000000000001)
test_expect_equal "$output" "thread:0000000000000001   2009-11-18 [4/4] Jjgod Jiang, Alexander Botero-Lowry; [notmuch] Mac OS X/Darwin compatibility issues (inbox tag-from-show-view unread)"

test_begin_subtest "Remove tag from notmuch-show view"
test_emacs '(notmuch-show "thread:0000000000000001") (notmuch-show-remove-tag "tag-from-show-view")'
output=$(notmuch search thread:0000000000000001)
test_expect_equal "$output" "thread:0000000000000001   2009-11-18 [4/4] Jjgod Jiang, Alexander Botero-Lowry; [notmuch] Mac OS X/Darwin compatibility issues (inbox unread)"

test_begin_subtest "Message with .. in Message-Id:"
add_message [id]=123..456@example '[subject]="Message with .. in Message-Id"'
test_emacs '(notmuch-search "id:\"123..456@example\"") (notmuch-test-wait) (notmuch-search-add-tag "search-add") (notmuch-search-add-tag "search-remove") (notmuch-search-remove-tag "search-remove") (notmuch-show "id:\"123..456@example\"") (notmuch-test-wait) (notmuch-show-add-tag "show-add") (notmuch-show-add-tag "show-remove") (notmuch-show-remove-tag "show-remove")'
output=$(notmuch search 'id:"123..456@example"' | notmuch_search_sanitize)
test_expect_equal "$output" "thread:XXX   2001-01-05 [1/1] Notmuch Test Suite; Message with .. in Message-Id (inbox search-add show-add)"

test_done
