#!/usr/bin/env bash

test_description="online help"
. test-lib.sh

test_expect_success 'notmuch --help' 'notmuch --help'
test_expect_success 'notmuch --help tag' 'notmuch --help tag'
test_expect_success 'notmuch help' 'notmuch help'
test_expect_success 'notmuch help tag' 'notmuch help tag'
test_expect_success 'notmuch --version' 'notmuch --version'

test_done
