# -*- makefile -*-

dir := test

smtp_dummy_srcs =		\
	$(notmuch_compat_srcs)	\
	$(dir)/smtp-dummy.c

smtp_dummy_modules = $(smtp_dummy_srcs:.c=.o)

$(dir)/smtp-dummy: $(smtp_dummy_modules)
	$(call quiet,CC) $^ -o $@

.PHONY: test check
test:	all $(dir)/smtp-dummy
	@${dir}/notmuch-test $(OPTIONS)

check: test

CLEAN := $(CLEAN) $(dir)/smtp-dummy
