# -*- makefile -*-

dir := test

smtp_dummy_srcs =		\
	$(notmuch_compat_srcs)	\
	$(dir)/smtp-dummy.c

smtp_dummy_modules = $(smtp_dummy_srcs:.c=.o)

$(dir)/smtp-dummy: $(smtp_dummy_modules)
	$(call quiet,CC) $^ -o $@

$(dir)/symbol-test: $(dir)/symbol-test.o
	$(call quiet,CC) $^ -o $@ -Llib -lnotmuch -lxapian

.PHONY: test check

test-binaries: $(dir)/smtp-dummy $(dir)/symbol-test

test:	all test-binaries
	@${dir}/notmuch-test $(OPTIONS)

check: test

CLEAN := $(CLEAN) $(dir)/smtp-dummy $(dir)/smtp-dummy.o $(dir)/symbol-test $(dir)/symbol-test.o
