#!/bin/sh

# Run tests
#
# Copyright (c) 2005 Junio C Hamano
#
# Adapted from a Makefile to a shell script by Carl Worth (2010)

cd $(dirname "$0")

# Clean up any results from a previous run
rm -r test-results >/dev/null 2>/dev/null

# Run the tests
for test in t[0-9][0-9][0-9][0-9]*.sh; do
	./"$test"
done

# Report results
./aggregate-results.sh test-results/t*-*

# Clean up
#rm -r test-results
