#!/usr/bin/env bash

test_description='the verbosity options of the test framework itself.'

. ./test-lib.sh || exit 1

test_begin_subtest 'print something in test_expect_success and pass'
test_expect_success '
  echo "hello stdout" &&
  echo "hello stderr" >&2 &&
  true
'
test_begin_subtest 'print something in test_expect_success and fail'
test_expect_success '
  echo "hello stdout" &&
  echo "hello stderr" >&2 &&
  false
'
test_begin_subtest 'print something between test_begin_subtest and test_expect_equal and pass'
echo "hello stdout"
echo "hello stderr" >&2
test_expect_equal "a" "a"

test_begin_subtest 'print something test_begin_subtest and test_expect_equal and fail'
echo "hello stdout"
echo "hello stderr" >&2
test_expect_equal "a" "b"

test_done
