#!/bin/bash

. ./perf-test-lib.sh

add_email_corpus

print_header

time_run 'initial notmuch new' 'notmuch new'
time_run 'second notmuch new' 'notmuch new'
time_run 'dump *' 'notmuch dump > tags.out'
time_run 'restore *' 'notmuch restore < tags.out'
time_run 'tag * +new_tag' "notmuch tag +new_tag '*'"

time_done
