# -*- makefile -*-

dir := util
extra_cflags += -I$(srcdir)/$(dir)

libutil_c_srcs := $(dir)/xutil.c $(dir)/error_util.c $(dir)/hex-escape.c \
		  $(dir)/string-util.c $(dir)/talloc-extra.c

libutil_modules := $(libutil_c_srcs:.c=.o)

$(dir)/libutil.a: $(libutil_modules)
	$(call quiet,AR) rcs $@ $^

SRCS := $(SRCS) $(libutil_c_srcs)
CLEAN := $(CLEAN) $(libutil_modules) $(dir)/libutil.a
