.TH NOTMUCH-PART 1 2011-12-04 "Notmuch 0.10.2"
.SH NAME
notmuch-part \- Output a single part of a multipart MIME message.
.SH SYNOPSIS

.B notmuch part
.BI "\-\-part=" "<part-number>"
.RI < search-terms >

.SH DESCRIPTION

The
.B part
command can used to output a single part of a multipart MIME message.

A single decoded MIME part, with no encoding or framing, is output to
stdout. The search terms must match only a single message, otherwise
this command will fail.

The part number should match the part "id" field output by the
"\-\-format=json" option of "notmuch show". If the message specified by
the search terms does not include a part with the specified "id" there
will be no output.

See the
.B "SEARCH SYNTAX"
section below for details of the supported syntax for <search-terms>.
.RE
